### ISSUE TITLE
Checking LFSystem Please wait

### ISSUE THREAD

**Issue by liupucn** [jagenjo/litefilesystem.js#10]
I can't open my LFSystem. 
when php install.php:
Notice: Undefined variable: owner in E:\Soft\xampp\Install path\www-data\editor\fileserver\src\install.php on line 155
 + All modules seem ready, nothing to do.
 - Code: 8 "Undefined variable: owner" File: E:\Soft\xampp\Install path\www-data\editor\fileserver\src\install.php Ln: 155

**Comment by jagenjo** [comment]
LiteFileSystem wasnt designed to work on windows, so I cannot help you on that.

**Comment by liupucn** [comment]
> LiteFileSystem并非旨在在Windows上运行，因此我无法为您提供帮助。
Thank you
