### ISSUE TITLE
Unable to update/overwrite file saved by admin in Public unit. Shows error "File belongs to other user"

### ISSUE THREAD

**Issue by KnightCoder** [jagenjo/litefilesystem.js#8]
The admin saved a project in Public unit. Another user edited the same file and trying to save it. But unable to save. No error message popup is shown for confirmation. However, when I realized that it has not save I noticed a message in the browser's console "File belongs to other user". 

Files in the public folder must be editable and savable  by another user. 

Is there any configuration or access that needs to be set for this to work?

**Comment by jagenjo** [comment]
No, files in the public folder are files used by the admin as a demo, so people have some resources to test.

If anybody could change them then the first user will erase them all.

**Comment by KnightCoder** [comment]
@jagenjo I think you might have thought this is specifically about https://webglstudio.org/demo/. Its not. When you clone the repo and try it yourself separately then we've noticed that it has this issue.
