### ISSUE TITLE
安装litefilesystem.js 

### ISSUE THREAD

**Issue by liupucn** [jagenjo/litefilesystem.js#9]
在安装Install.php时：
 - Code: 1 "Uncaught Error: Call to undefined function posix_getgrgid() in E:\Soft\xampp\Install path\Myhtdocs\editor\fileserver\src\include\modules\system.php:220
Stack trace:
#0 E:\Soft\xampp\Install path\Myhtdocs\editor\fileserver\src\install.php(143): SystemModule->checkReady()
#1 {main}
  thrown" File: E:\Soft\xampp\Install path\Myhtdocs\editor\fileserver\src\include\modules\system.php Ln: 220

**Comment by atlasan** [comment]
check this [https://github.com/jagenjo/litefilesystem.js/issues/7](url)

**Comment by atlasan** [comment]
check this [https://github.com/jagenjo/litefilesystem.js/issues/7#issue-601783844](url)
